### ISSUE TITLE
Invalid folder structure

### ISSUE THREAD

**Issue by LemADEC** [SoraZodia/Cannibalism#10]
As of Cannibalism-3.1.0-1.10.2.jar, the mod tries to recreate config/saves folder structure in a Windows client scheme on Unix dedicated servers.
More specifically, the following files and folders are generated on Unix dedicated servers:
- config\cannibalism folder, should be config/cannibalism
- .\saves\Twinkle\SavedPlayerData, should be Twinkle/data
- .\saves\Twinkle\SavedPlayerData\cannibalismData.dat, should be Twinkle/data/cannibalismData.dat

Because those folders are non  standard, it prevents the map to be backup properly.

I suspect this will also fail to support Unix clients using the mod.

**Comment by LemADEC** [comment]
From what I remember, the default folder is the world directory, so you can just open "data" folder, then open a "cannibalismData.dat" file in there.

The config folder can be retrieved from the FMLPreInitializationEvent like so:
event.getModConfigurationDirectory().getAbsolutePath()

**Comment by SoraZodia** [comment]
The mod does use that, but I derped up in creating the path when I made the code. It should be an easy fix.

**Comment by SoraZodia** [comment]
v2.1.0 should have that fixed, let me know if the problem is still there. Although, server-side, the path would still be ./saves/Twinkle/... but that shouldn't cause any problems.

**Comment by LemADEC** [comment]
did you mean 3.2.0?

**Comment by SoraZodia** [comment]
Opps, I meant 5.1.0.
And... Shit, I've been thinking you were on Minecraft 1.12.2, and fixed it
on that version.

I'll see about backporting the fix to Minecraft 1.10.2 though.

**Comment by LemADEC** [comment]
Yes, please :)

**Comment by SoraZodia** [comment]
v3.1.1 for Minecraft 1.10.2 should have the fix now, let me know if the problem is still there.
