### ISSUE TITLE
Cannibalism may be screwing with the /kill command

### ISSUE THREAD

**Issue by Sunconure11** [SoraZodia/Cannibalism#13]
Log used: https://www.dropbox.com/s/64756ohyfncuyrk/latest%20%282%29.log?dl=0

> Sunconure11 - Today at 8:12 PM
> i also have this installed into the same instance
> and yes, i can get you a log
> https://minecraft.curseforge.com/projects/fps-reducer
> Minecraft CurseForge
> FPS Reducer
> Reduce GPU and CPU usage automatically when no user operation exists.
> 
> Attachment file type: document
> latest.log
> 1.58 MB
> ill also send over the current build of my pack in curse instance form, just in case you feel like debugging it
> Attachment file type: archive
> CM_1.12.2-just_in_case.zip
> 6.07 MB
> even though im waiting on a fix for chisel and bits
> ZombieHDGaming - Today at 8:16 PM
> Well, I'd suggest seeing if any other mods need updating, cause I can see Quark is throwing the BWM error, even though it's been fixed in the latest release
> Sunconure11 - Today at 8:17 PM
> kept noticing it a few times over the past few days, but i didn't think much of it, but its becoming annoying now
> also, i do not have BWM in my pack
> ZombieHDGaming - Today at 8:18 PM
> I figured, it was an error with Quark when it wasn't included (I think). Vazkii fixed it in the last release of Quark. And I'm still scrolling the log though, so I might see something else
> Sunconure11 - Today at 8:19 PM
> looks like a few things needed updating but i don't believe they were behind this
> said mods were forgelin, JEI, and NEAT
> ZombieHDGaming - Today at 8:20 PM
> I know, I was just suggesting you should still though. So far, I see RandomPatches does something with the NetHandlerPlayClient, so it could be an issue. And try updating Quark, cause it does seem like an outdated version
> Sunconure11 - Today at 8:21 PM
> quark is at the latest curse uses
> ZombieHDGaming - Today at 8:21 PM
> That's odd, cause the BWM API console print was fixed and it's in your log
> Well, I've noticed quite a few errors from mowziesmobs in the log, so that might need to be looked into. I'm finally about halfway though the log though
> Apparently there is also something from Repose, but I'll need to look at the mod before I can assume anything
> Sunconure11 - Today at 8:31 PM
> https://minecraft.curseforge.com/projects/repose
> Minecraft CurseForge
> Repose
> This mod allows you to walk up and down hills without jumping. Give your spacebar a break!
> 
> ZombieHDGaming - Today at 8:33 PM
> Looks like the /kill error might've been caused by cannibalism trying to do something during the death event and failing to do so, but the actual command could've just be a weird interference with FTBU
> Yeah, the /kill error is definitely cannibalism messing up. So that's one answer. Now to figure out why you're randomly frozen
> Sunconure11 - Today at 8:36 PM
> https://github.com/SoraZodia/Cannibalism
> GitHub
> SoraZodia/Cannibalism
> Cannibalism - Adds in the aspect of eating villagers... or yourself
> 
> ZombieHDGaming - Today at 8:41 PM
> Well, after nearly a 15,000 line log, I can't see anything that would cause a player to randomly freeze after they stop moving. I'll make a report to Cannibalism about that issue, but does the freeze issue occur without VF?
> Sunconure11 - Today at 8:42 PM
> i have not tested yet, though ill look when i can
> ZombieHDGaming - Today at 8:42 PM
> Please do, cause I have a feeling that isn't caused by VF
> Sunconure11 - Today at 8:46 PM
> ill also see how common this issue is, though i have been working on some things in the pack at the moment which makes it a bit harder to test
> mainly, im working on a crimson cult-themed structure
> and i can't test now anyways, it looks like my update fucked up another mod
> luckily i have a clue as to whats going on
> also, while you're at it, maybe report the issues relating to mowzies mobs to the dev as well
> https://github.com/BobMowzie/MowziesMobs
> GitHub
> BobMowzie/MowziesMobs
> Contribute to MowziesMobs development by creating an account on GitHub.
> 
> the crash i encountered was more clear cut, i think forgelin is no longer compatible with better records

**Comment by SoraZodia** [comment]
Looks like I need to check my death event, I'll see what I can find

**Comment by SoraZodia** [comment]
Well shit, I messed up my Optionals. I should be able to get a fix out somewhere this week.

**Comment by SoraZodia** [comment]
Should be fixed now with v5.1.4, let me know if it's still there

**Comment by Sunconure11** [comment]
Issue is gone.
