### ISSUE TITLE
[Suggestion] Add in support for other mods with Wendigos such as Lycanites mobs

### ISSUE THREAD

**Issue by DWX12** [SoraZodia/Cannibalism#14]
Would like to see mod integration with other mods if your mod detects other compatible mods that are loaded. If possible and within your capabilities.

Would it also be possible to add in a config option for players to change the Wendigo mob to a mob of their choice?

Just an idea, cool mod otherwise and thank you.

**Comment by SoraZodia** [comment]
I did considered, but nothing came to mind. I'll try to look into it. I won't make an option to change the Wendigo mob, it wouldn't make much sense.

**Comment by DWX12** [comment]
It was just an idea for people and modpack makers to have more options. Good work though and thanks for the reply.

**Comment by SoraZodia** [comment]
This is long overdue, but the mod's development has been moved to another dev (https://github.com/MoriyaShiine/wendigoism). 

Sorry, I was not able to add support for the other mods.
