### ISSUE TITLE
[SUGGESTION] Add support for other modded body parts as food for the wendigo

### ISSUE THREAD

**Issue by Sunconure11** [SoraZodia/Cannibalism#15]
I.e Thaumcraft's brain would be a good example. Perhaps a config would be useful, too?

**Comment by SoraZodia** [comment]
There is a bit of support in the form of a config added in v5.4.0. Currently, it will just cause the player's wendigo level to increase by a specified amount. I'll see about improving it on the next update.

**Comment by SoraZodia** [comment]
This is long overdue, but the mod's development has been moved to another dev (https://github.com/MoriyaShiine/wendigoism). 

Sorry, I didn't managed to get around in improving the config for body parts added by other mods.
