### ISSUE TITLE
[Suggestion] Config options to disable the various other knives and other options

### ISSUE THREAD

**Issue by DWX12** [SoraZodia/Cannibalism#16]
Would like to see config options to disable the various knives. Not just their recipes, but from showing up in JEI, if in your ability. Not entirely sure what the differences between them are except for being different tiers.

Two config other options I'd like to see would to be able to define any and all "knives" or tools that one could use to obtain their and other entities flesh. Of course, a disclaimer for any item that has a right click ability would have to be added.

The second idea would be for a config option to define what sound to use for injury and one for no sound at all. There are a couple of mods out that already that let users define sounds such as Random Tweaks, Dynamic Surroundings, and possibly Ding.

Again, thank you for such a cool mod.

**Comment by SoraZodia** [comment]
I could add the option for the tools and sounds. Not too sure about the config to define additional knifes, I remember trying to add that in before and not having the proper hooks to do it, I'll look into it again through.

**Comment by SoraZodia** [comment]
v5.4.0 should let you disable the individual knifes other than the dev knife, it does require MC to restart however. I'll see if I can add in custom sounds on the next update.

**Comment by DWX12** [comment]
Awesome! Thanks alot for this. Feel free to close this then unless you want to keep it open for the sound option.

**Comment by SoraZodia** [comment]
I'm going to keep it open for the sound option, since that was part of the original suggestion

**Comment by SoraZodia** [comment]
v5.6.0 should allow you to use an resource pack to define custom sounds for the knife, although since the knife uses Minecraft's own sounds, you would have to enable that option in the configs (set "Use Custom Scream" to true). You will be able to disable the sounds completely by setting "Mute Scream Sound" to true.
