### ISSUE TITLE
[question] What is the entity ID for altering the player?

### ISSUE THREAD

**Issue by Winddbourne** [SoraZodia/Cannibalism#17]
I'd like to change the damage amount done to the player and potentially add blood drops as well. In the pack I'm working on I start the players out with only 3 hearts so it would be really nice to lower self-damage a bit for the early game. 

The problem I'm having is that the sample document doesn't include me and I can't click on myself with the dev knife; that just reloads the scripts.

**Comment by SoraZodia** [comment]
ah... That got overlooked when I had made the configs, I'll see about adding support for that soon.

**Comment by SoraZodia** [comment]
Support for that has been added in v5.5.0, you can use "player" as the entityID and set the min/max damage like normal. Only different is that you can't set customs drops for the player.
