### ISSUE TITLE
[Suggestion/Tweak] Updated Textures and Wendigo Mob

### ISSUE THREAD

**Issue by cybercat5555** [SoraZodia/Cannibalism#19]
Hello, I've made a set up updated textures, seen below. I've also fixed the model json of the knives so they are held more like knives. I have also created a revised Wendigo model if you're interested.

Check out the revised item textures here: https://imgur.com/a/YA2W2mn
Folder of item textures and knife jsons: https://drive.google.com/drive/folders/1SANZ-yWpbJath0jPqETFlfeZdZe5pZqK?usp=sharing

Lemme know if you want the model/textures for the wendigo, if so I'll give you a private link via Curseforge.

**Comment by SoraZodia** [comment]
They look great! I'm interested in the wendigo model as well.

**Comment by cybercat5555** [comment]
hm, since it seems Curseforge has changed its layout (seems it removed dms?) here's a link to the wendigo assets
https://drive.google.com/open?id=1zb6KioxO7-LH6Eqjkmonc6gTPj9ONtRL

**Comment by SoraZodia** [comment]
The new model and texture is implemented in v5.6.0, thanks again for your help :)
