### ISSUE TITLE
broken with graves

### ISSUE THREAD

**Issue by UnlimitedTurtlez** [SoraZodia/Cannibalism#20]
with any gravestone mod the player meat drop will sometimes take priority and get caught in the grave and cause the player inventory to delete cuz the meat registered in the grave and not the inventory

**Comment by SoraZodia** [comment]
I set its priority to the lowest I could set it, v5.6.2 should have that change in. This sounds like it could be a tricky bug to fix, but I'll try my best to fix it if it still happens.
