### ISSUE TITLE
Unnatural hunger [Suggestions]

### ISSUE THREAD

**Issue by shoverno2** [SoraZodia/Cannibalism#21]
I know that maybe you not supposed to adding any compatibility. But there one interesting effect in thaumcraft. When warp become too big player gains random effect. One of those is "Unnatural hunger". It's high dangerous effect, if player doesn't have any rotten flesh in inventory. Any other food can't remove this effect. So, maybe, you can add any cannibalism food as resolve of this effect? This will looking good at all)

**Comment by SoraZodia** [comment]
I'm not against adding support for other mods, but it is something I don't put too much focus to. That said, hunger is something tied to the myth-based portion of the mod, and adding said feature would contradict the idea behind it.
