### ISSUE TITLE
wendigo_villager and Security Craft Turret Crash

### ISSUE THREAD

**Issue by DSolde3** [SoraZodia/Cannibalism#22]
When a turret shoots a wendigo villager the client and server crash.

Cannibalism-5.6.3-1.12.2

**Comment by SoraZodia** [comment]
Can I take a look at the crash log?

**Comment by DSolde3** [comment]
McLib core mod (mclib-1.0.4-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 3/15/20 11:23 PM
Description: Ticking entity

java.lang.ClassCastException: net.geforcemods.securitycraft.entity.EntityBullet cannot be cast to net.minecraft.entity.EntityLivingBase
	at sorazodia.cannibalism.mob.EntityTurnedVillager.func_70097_a(EntityTurnedVillager.java:73)
	at net.geforcemods.securitycraft.entity.EntityBullet.func_184549_a(EntityBullet.java:29)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:267)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at sorazodia.cannibalism.mob.EntityTurnedVillager.func_70097_a(EntityTurnedVillager.java:73)
	at net.geforcemods.securitycraft.entity.EntityBullet.func_184549_a(EntityBullet.java:29)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:267)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: securitycraft:bullet (net.geforcemods.securitycraft.entity.EntityBullet)
	Entity ID: 382
	Entity Name: Bullet
	Entity's Exact location: -2579.32, 73.13, -1326.91
	Entity's Block location: World: (-2580,73,-1327), Chunk: (at 12,4,1 in -162,-83; contains blocks -2592,0,-1328 to -2577,255,-1313), Region: (-6,-3; contains chunks -192,-96 to -161,-65, blocks -3072,0,-1536 to -2561,255,-1025)
	Entity's Momentum: 1.20, 0.38, 0.70
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['ImSoldee'/201, l='world', x=-2576.81, y=70.00, z=-1338.85]]
	Chunk stats: ServerChunkCache: 1268 Drop: 0
	Level seed: 6430129141330618310
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-2178,69,-960), Chunk: (at 14,4,0 in -137,-60; contains blocks -2192,0,-960 to -2177,255,-945), Region: (-5,-2; contains chunks -160,-64 to -129,-33, blocks -2560,0,-1024 to -2049,255,-513)
	Level time: 3993101 game time, 342114 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 83800 (now: false), thunder time: 57142 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-72-generic
	Java Version: 1.8.0_242, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 6597355392 bytes (6291 MB) / 8091860992 bytes (7717 MB) up to 8091860992 bytes (7717 MB)
	JVM Flags: 2 total; -Xmx8192M -Xms8192M
	IntCache: cache: 0, tcache: 0, allocated: 5, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 63 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version           | Source                                        | Signature                                |
	|:------ |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99         | custom.jar                                    | None                                     |
	| LCHIJA | forge               | 14.23.5.2847      | custom.jar                                    | None                                     |
	| LCHIJA | creativecoredummy   | 1.0.0             | minecraft.jar                                 | None                                     |
	| LCHIJA | openmodscore        | 0.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | futuremccore        | 0.1.12            | minecraft.jar                                 | None                                     |
	| LCHIJA | securitycraft       | v1.8.17           | [1.12.2] SecurityCraft v1.8.17.jar            | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCHIJA | bookshelf           | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | buildcraftlib       | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | ic2                 | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | jei                 | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHIJA | forestry            | 5.8.2.387         | forestry_1.12.2-5.8.2.387.jar                 | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                  | None                                     |
	| LCHIJA | cannibalism         | 5.6.3             | Cannibalism-5.6.3-1.12.2.jar                  | None                                     |
	| LCHIJA | chesttransporter    | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar             | None                                     |
	| LCHIJA | chisel              | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                  | None                                     |
	| LCHIJA | morpheus            | 1.12.2-3.5.106    | Morpheus-1.12.2-3.5.106.jar                   | None                                     |
	| LCHIJA | comforts            | 1.4.1.3           | comforts-1.12.2-1.4.1.3.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | opframe             | 1.4.0             | OnlinePicFrame_v1.4.35_mc1.12.2.jar           | None                                     |
	| LCHIJA | playerrevive        | 1.0               | PlayerRevive_v1.2.31_mc1.12.2.jar             | None                                     |
	| LCHIJA | creativecore        | 1.10.0            | CreativeCore_v1.10.3_mc1.12.2.jar             | None                                     |
	| LCHIJA | props               | 2.6.3             | Decocraft-2.6.3_1.12.2.jar                    | None                                     |
	| LCHIJA | dynamictrees        | 1.12.2-0.9.7      | DynamicTrees-1.12.2-0.9.7.jar                 | None                                     |
	| LCHIJA | dynamictreesbop     | 1.12.2-1.4.1e     | DynamicTreesBOP-1.12.2-1.4.1e.jar             | None                                     |
	| LCHIJA | mclib               | 1.0.4             | mclib-1.0.4-1.12.2.jar                        | None                                     |
	| LCHIJA | emoticons           | 0.4.3             | emoticons-0.4.3-1.12.2-dist.jar               | None                                     |
	| LCHIJA | eplus               | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | extrautils2         | 1.0               | extrautils2-1.12-1.9.9.jar                    | None                                     |
	| LCHIJA | fastfurnace         | 1.3.1             | FastFurnace-1.12.2-1.3.1.jar                  | None                                     |
	| LCHIJA | fastbench           | 1.7.3             | FastWorkbench-1.12.2-1.7.3.jar                | None                                     |
	| LCHIJA | fencejumper         | 1.0.5             | fencejumper-1.12-1.0.5.jar                    | None                                     |
	| LCHIJA | fenceoverhaul       | 1.3.4             | FenceOverhaul-1.3.4.jar                       | None                                     |
	| LCHIJA | ftbbackups          | 1.1.0.1           | FTBBackups-1.1.0.1.jar                        | None                                     |
	| LCHIJA | ftblib              | 5.4.7.0           | FTBLib-5.4.7.0.jar                            | None                                     |
	| LCHIJA | ftbutilities        | 5.4.0.124         | FTBUtilities-5.4.0.124.jar                    | None                                     |
	| LCHIJA | cfm                 | 6.3.1             | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCHIJA | minecraftfuture     | 0.1.13            | future-mc-0.1.13.jar                          | None                                     |
	| LCHIJA | ido                 | 1.0.6             | ido-1.12.2-1.1.0.jar                          | None                                     |
	| LCHIJA | improvedbackpacks   | 1.12.2-1.4.1.0    | ImprovedBackpacks-1.12.2-1.4.1.0.jar          | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.7.0      | journeymap-1.12.2-5.7.0.jar                   | None                                     |
	| LCHIJA | mca                 | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                | None                                     |
	| LCHIJA | mychunkloader       | 1.12.2-01         | MyChunkloader-1.12.2-01.jar                   | None                                     |
	| LCHIJA | openmods            | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks          | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | placebo             | 1.6.0             | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCHIJA | radixcore           | 1.12.x-2.2.1      | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| LCHIJA | reap                | 1.5.2             | reap-1.5.2.jar                                | None                                     |
	| LCHIJA | rustic              | 1.1.2             | rustic-1.1.2.jar                              | None                                     |
	| LCHIJA | simplecore          | 1.7.3.4           | simplecore-1.12.2-1.7.3.4.jar                 | None                                     |
	| LCHIJA | simpleores          | 1.11.2.0          | simpleores-1.12.2-1.11.2.0.jar                | None                                     |
	| LCHIJA | spartanshields      | 1.5.4             | SpartanShields-1.12.2-1.5.4.jar               | None                                     |
	| LCHIJA | tombstone           | 3.6.9             | tombstone-3.6.9-1.12.2.jar                    | None                                     |
	| LCHIJA | torchslabmod        | v1.5              | torchslabmod-1.12.2_v1.5.jar                  | None                                     |
	| UD     | mclib_core          | 1.0.4             | minecraft.jar                                 | None                                     |

	Loaded coremods (and transformers): 
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.3_mc1.12.2.jar)
  
McLib core mod (mclib-1.0.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Profiler Position: N/A (disabled)
	Player Count: 1 / 10; [EntityPlayerMP['ImSoldee'/201, l='world', x=-2576.81, y=70.00, z=-1338.85]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by SoraZodia** [comment]
v5.6.4 should have the fix, let me know if it's still happening
