### ISSUE TITLE
Not can I disable the player flesh drop when dying  or not can I lower the thighs that go up.

### ISSUE THREAD

**Issue by DeathSmurf** [SoraZodia/Cannibalism#23]
His mod is great but how can I disable the player flesh drop when dying? Or how can I lower the thighs that go up? The Mod makes Pam's harvest craft useless. 

**was there any way to make this possible?**

**Comment by SoraZodia** [comment]
Sorry, but the flesh drops are one of the core features of the mod, I won't be adding any options to disable it or lower its drop rates.
