### ISSUE TITLE
Curse project page displays Typo in screenshot

### ISSUE THREAD

**Issue by tyrope** [SoraZodia/Cannibalism#3]
The [curse project page](http://minecraft.curseforge.com/projects/cannibalism) shows a typo in the options menu.

In particular, this image:
![Options menu screenshot](http://i.imgur.com/NNJTro9.png)

This should say 'pitch' and not 'pinch'?

**Comment by SoraZodia** [comment]
Ahhh... Opps, I'll fix that typo.
