### ISSUE TITLE
1.11.2 Release?

### ISSUE THREAD

**Issue by al132** [SoraZodia/Cannibalism#6]
Hey there, i'm just curious to see if you had any intention of releasing this mod for 1.11 in the near future? I saw briefly in the commits that you had done some porting (if not all of it). I'm remaking a [skyblock pack](https://minecraft.curseforge.com/projects/all-the-mods-presents-sacrificial-skies) for 1.11 that I had originally made on 1.10 which featured this mod, and this is pretty much the only missing piece left.

Please let me know where the project is at, thanks.

**Comment by SoraZodia** [comment]
I thought I had released it already... It should be up by the end of this
weekend.
