### ISSUE TITLE
[SUGGESTION] Configurable hunger drop rates in mythological mode

### ISSUE THREAD

**Issue by Sunconure11** [SoraZodia/Cannibalism#8]
In mythological mode, hunger drops rather fast, and I'd like an option to slow it, including even to vanilla speed, if possible. I had misinterpreted this as a bug when it was first turned on by me on my own pack.

**Comment by SoraZodia** [comment]
Having it configurable is a bit out of the question, the hunger drain was to reference the Wendigo's insatiability and I don't want players to be able to change that. I can try to add ways in-game to slow the drain though.

Other than that, the mod already have a few ways to deal with the hunger drain: 
Killing an Wendigo will revert your hunger drain back to vanilla speed, although you will lose your buffs. Aside from that, the Fleshs' hunger gain and saturation will get bigger as you cannibalize more and more.

**Comment by SoraZodia** [comment]
Added a few methods to changed your wendigo levels (indirectly impacting the hunger drain) in the recent versions. More may be add in the future, but for now, I will consider this closed.
